// src/components/MainView.tsx
import type { ComponentType } from "react";
import AtivacaoWindows from "./features/AtivacaoWindows";
import AtivacaoOffice from "./features/AtivacaoOffice";
import LimpaCacheDNS from "./features/LimpaCacheDNS";
import LimpaSpoolImpressao from "./features/LimpaSpoolImpressao";
import DesativaHibernacao from "./features/DesativaHibernacao";
import AjustarHoraFormatacao from "./features/AjustarHoraFormatacao";
import CorrigirCompartilhamento from "./features/CorrigirCompartilhamento";
import AtivarProtecaoSistema from "./features/AtivarProtecaoSistema";
import BloqueadorFirewall from "./features/BloqueadorFirewall";
import RestaurarPhotoViewer from "./features/RestaurarPhotoViewer";
import AlterarLayoutTeclado from "./features/AlterarLayoutTeclado";
import AtivarGpedit from "./features/AtivarGpedit";
import AgendarDesligamento from "./features/AgendarDesligamento";

interface FeatureProps {
  onVoltar: () => void;
}

const COMPONENTES: Record<string, ComponentType<FeatureProps>> = {
  "Ativação do Windows": AtivacaoWindows,
  "Ativação do Office": AtivacaoOffice,
  "Limpar Cache DNS": LimpaCacheDNS,
  "Limpar e Reiniciar Spool de Impressão": LimpaSpoolImpressao,
  "Desativar Hibernação do Windows": DesativaHibernacao,
  "Ajustar Hora da Formatação": AjustarHoraFormatacao,
  "Corrigir Compartilhamento de Rede": CorrigirCompartilhamento,
  "Ativar Proteção do Sistema": AtivarProtecaoSistema,
  "Bloqueador de Programas no Firewall": BloqueadorFirewall,
  "Restaurar Visualizador de Fotos": RestaurarPhotoViewer,
  "Alterar Layout do Teclado": AlterarLayoutTeclado,
  "Ativar Gpedit.msc (Home)": AtivarGpedit,
  "Agendar Desligamento": AgendarDesligamento,
};

interface MainViewProps {
  visao: string;
  onVoltar: () => void;
}

function MainView({ visao, onVoltar }: MainViewProps) {
  const Componente = COMPONENTES[visao];

  if (!Componente) {
    return <p>Erro: funcionalidade "{visao}" não encontrada.</p>;
  }

  return <Componente onVoltar={onVoltar} />;
}

export default MainView;

// frontend/src/components/MainView.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import AtivacaoWindows from "./features/AtivacaoWindows.svelte";
  import AtivacaoOffice from "./features/AtivacaoOffice.svelte";
  import LimpaCacheDNS from "./features/LimpaCacheDNS.svelte";
  import DesativaHibernacao from "./features/DesativaHibernacao.svelte";
  import LimpaSpoolImpressao from "./features/LimpaSpoolImpressao.svelte";
  import AgendarDesligamento from "./features/AgendarDesligamento.svelte";
  import AjustarHoraFormatacao from "./features/AjustarHoraFormatacao.svelte";
  import CorrigirCompartilhamento from "./features/CorrigirCompartilhamento.svelte";
  import AlterarLayoutTeclado from "./features/AlterarLayoutTeclado.svelte";
  import FeatureRunner from "./features/FeatureRunner.svelte";

  export let visao;

  const dispatch = createEventDispatcher();

  function handleVoltar() {
    dispatch("navigate", "Painel de Informações");
  }
</script>

<div class="w-full h-full">
  {#if visao === "Painel de Informações"}
    <p>Erro: Visão do Painel deveria ser tratada pelo App.svelte</p>
  {:else if visao === "Windows - Ativação"}
    <AtivacaoWindows on:voltar={handleVoltar} />
  {:else if visao === "Office - Ativação"}
    <AtivacaoOffice on:voltar={handleVoltar} />
  {:else if visao === "Corrige Compartilhamento de Rede"}
    <CorrigirCompartilhamento on:voltar={handleVoltar} />
  {:else if visao === "Limpa cache DNS"}
    <LimpaCacheDNS on:voltar={handleVoltar} />
  {:else if visao === "Desativa a Hibernação do Windows"}
    <DesativaHibernacao on:voltar={handleVoltar} />
  {:else if visao === "Limpa e Reinicia Spool de Impressao"}
    <LimpaSpoolImpressao on:voltar={handleVoltar} />
  {:else if visao === "Agendar Desligamento"}
    <AgendarDesligamento on:voltar={handleVoltar} />
  {:else if visao === "Ajustar Hora da Formatação"}
    <AjustarHoraFormatacao on:voltar={handleVoltar} />
  {:else if visao === "Alterar Layout do Teclado"}
    <AlterarLayoutTeclado on:voltar={handleVoltar} />
  {:else}
    <FeatureRunner
      titulo={visao}
      descricao="Esta funcionalidade ainda está em desenvolvimento."
      textoBotao="Indisponível"
      emExecucao={true}
      on:voltar={handleVoltar}
    />
  {/if}
</div>
