// frontend/src/components/shared/BotaoVoltar.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";

  const dispatch = createEventDispatcher();
</script>

<button
  class="w-fit mt-6 p-2.5 px-5 border border-primary-purple bg-transparent text-text-light rounded-lg cursor-pointer text-base font-bold transition-all duration-200 hover:bg-primary-purple block mx-auto"
  on:click={() => dispatch("click")}
>
  &larr; Voltar ao Painel Principal
</button>

// src/components/shared/BotaoVoltar.tsx
interface BotaoVoltarProps {
  onClick: () => void;
}

function BotaoVoltar({ onClick }: BotaoVoltarProps) {
  return (
    <button
      className="mx-auto mt-6 block w-fit cursor-pointer rounded-lg border border-structural-purple bg-transparent p-2.5 px-5 text-base font-bold text-text-light transition-all duration-200 hover:bg-structural-purple"
      onClick={onClick}
    >
      &larr; Voltar ao Painel Principal
    </button>
  );
}

export default BotaoVoltar;
