// frontend/src/components/shared/LogPanel.svelte
<script lang="ts">
  export let logLines: string[] = [];

  function autoscroll(node: HTMLElement) {
    function scrollToBottom() {
      // Pequeno timeout para garantir que o DOM foi atualizado antes do scroll
      setTimeout(() => {
        node.scrollTop = node.scrollHeight;
      }, 0);
    }

    scrollToBottom();

    return {
      update() {
        scrollToBottom();
      },
    };
  }
</script>

<div
  class="bg-dark-blue-bg bg-opacity-50 rounded-lg mt-5 p-4 overflow-y-auto text-sm border border-gray-700 scroll-smooth flex-grow min-h-0"
  use:autoscroll
>
  <pre
    class="m-0 whitespace-pre-wrap break-words font-mono text-text-light">{logLines.join(
      "\n",
    )}</pre>
</div>

// src/components/shared/LogPanel.tsx
import { useEffect, useRef } from "react";

interface LogPanelProps {
  logLines: string[];
}

/** Painel de log com auto-scroll para a última linha, igual ao legado. */
function LogPanel({ logLines }: LogPanelProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const node = containerRef.current;
    if (node) {
      node.scrollTop = node.scrollHeight;
    }
  }, [logLines]);

  return (
    <div
      ref={containerRef}
      className="mt-5 min-h-0 flex-grow scroll-smooth overflow-y-auto rounded-lg border border-gray-700 bg-dark-blue-bg/50 p-4 text-sm"
    >
      <pre className="m-0 whitespace-pre-wrap break-words font-mono text-text-light">
        {logLines.join("\n")}
      </pre>
    </div>
  );
}

export default LogPanel;
