// src/components/features/LimpaSpoolImpressao.tsx
import { useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import FeatureContainer from "../shared/FeatureContainer";
import LogPanel from "../shared/LogPanel";
import BotaoVoltar from "../shared/BotaoVoltar";

interface LimpaSpoolImpressaoProps {
  onVoltar: () => void;
}

function LimpaSpoolImpressao({ onVoltar }: LimpaSpoolImpressaoProps) {
  const [logLines, setLogLines] = useState<string[]>(["Aguardando início..."]);
  const [emExecucao, setEmExecucao] = useState(false);

  function adicionarLog(mensagem: string) {
    const timestamp = new Date().toLocaleTimeString("pt-BR");
    setLogLines((prev) => [...prev, `[${timestamp}] ${mensagem}`]);
  }

  async function iniciar() {
    setEmExecucao(true);
    setLogLines(["Iniciando limpeza e reinício do Spool de Impressão..."]);

    try {
      adicionarLog("Parando o serviço Spooler, removendo arquivos travados e reiniciando...");
      const arquivosRemovidos = await invoke<number>("limpar_spool_impressao");
      adicionarLog(`${arquivosRemovidos} arquivo(s) de spool travado(s) removido(s).`);
      adicionarLog("Problemas de impressoras travadas devem estar resolvidos.");
      adicionarLog("--- Operação concluída ---");
    } catch (err) {
      adicionarLog(`ERRO: ${err}`);
      adicionarLog("--- Operação finalizada com erro ---");
    } finally {
      setEmExecucao(false);
    }
  }

  return (
    <FeatureContainer titulo="Limpar e Reiniciar Spool de Impressão">
      <div className="flex min-h-0 flex-grow flex-col">
        <div className="mx-auto w-full max-w-xl flex-shrink-0 pr-2">
          <p className="mb-6 mt-0 text-center opacity-90">
            Para o serviço de Spooler de Impressão, remove arquivos de fila travados e reinicia o
            serviço — útil para resolver problemas de impressoras travadas.
          </p>
          <button
            className="mt-4 w-full cursor-pointer rounded-lg border-none bg-accent-orange p-4 text-xl font-bold text-dark-blue-bg transition-all duration-200 hover:brightness-110 disabled:cursor-not-allowed disabled:bg-gray-600"
            onClick={iniciar}
            disabled={emExecucao}
          >
            {emExecucao ? "Executando..." : "Executar Limpeza"}
          </button>
        </div>

        <LogPanel logLines={logLines} />
      </div>

      <div className="flex-shrink-0 pt-4">
        <BotaoVoltar onClick={onVoltar} />
      </div>
    </FeatureContainer>
  );
}

export default LimpaSpoolImpressao;

// frontend/src/components/features/LimpaSpoolImpressao.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { ExecutarComando } from '../../../wailsjs/go/main/App';
  import FeatureRunner from './FeatureRunner.svelte';

  const dispatch = createEventDispatcher();

  let logLines: string[] = ["Aguardando início..."];
  let emExecucao = false;

  async function iniciar() {
    emExecucao = true;
    logLines = ["Iniciando limpeza e reinício do Spool de Impressão..."];

    try {
      adicionarLog("Parando o serviço Spooler...");
      const resultStop = await ExecutarComando("net", ["stop", "spooler"]);
      adicionarLog("Resultado: " + resultStop);

      adicionarLog("Aguardando 3 segundos antes de reiniciar...");
      await new Promise(resolve => setTimeout(resolve, 3000));

      adicionarLog("Reiniciando o serviço Spooler...");
      const resultStart = await ExecutarComando("net", ["start", "spooler"]);
      adicionarLog("Resultado: " + resultStart);

      adicionarLog("Problemas de impressoras travadas devem estar resolvidos.");
      adicionarLog("--- Operação concluída ---");
    } catch (err) {
      adicionarLog(`ERRO: ${err}`);
      adicionarLog("--- Operação finalizada com erro ---");
    }
  }

  function adicionarLog(mensagem: string) {
    const timestamp = new Date().toLocaleTimeString("pt-BR");
    logLines = [...logLines, `[${timestamp}] ${mensagem}`];
    if (mensagem.includes("---")) {
      emExecucao = false;
    }
  }
</script>

<FeatureRunner
  titulo="Limpar e Reiniciar Spool de Impressão"
  descricao="Para e reinicia o serviço de Spooler de Impressão, útil para resolver problemas de impressoras travadas."
  textoBotao="Executar Limpeza"
  bind:logLines
  bind:emExecucao
  on:start={iniciar}
  on:voltar={() => dispatch('voltar')}
/>
